version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: document_qa
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
