apiVersion: v1
kind: Service
metadata:
  name: docqa-redis
spec:
  selector:
    app: docqa-redis
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None  # 设置为 Headless Service 也可换成 ClusterIP
